services:
  dogbot:
    container_name: dogbot
    build: .
    image: dogbot9000
    labels:
      glance.name: Dogbot9000
      glance.icon: assets/discord.svg
      glance.description: Discord bot
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./pic:/app/pic
      - ./logs:/app/logs
